SECTOR_ETFS = {
    "XLK": {"name": "Technology Select Sector SPDR", "sector": "Technology", "color": "#58a6ff"},
    "XLV": {"name": "Health Care Select Sector SPDR", "sector": "Health Care", "color": "#3fb950"},
    "XLF": {"name": "Financial Select Sector SPDR", "sector": "Financials", "color": "#f0883e"},
    "XLE": {"name": "Energy Select Sector SPDR", "sector": "Energy", "color": "#f85149"},
    "XLI": {"name": "Industrial Select Sector SPDR", "sector": "Industrials", "color": "#a5d6ff"},
    "XLY": {"name": "Consumer Discretionary Select SPDR", "sector": "Consumer Discretionary", "color": "#d2a8ff"},
    "XLP": {"name": "Consumer Staples Select Sector SPDR", "sector": "Consumer Staples", "color": "#7ee787"},
    "XLB": {"name": "Materials Select Sector SPDR", "sector": "Materials", "color": "#ffa657"},
    "XLRE": {"name": "Real Estate Select Sector SPDR", "sector": "Real Estate", "color": "#79c0ff"},
    "XLU": {"name": "Utilities Select Sector SPDR", "sector": "Utilities", "color": "#ff7b72"},
    "XLC": {"name": "Communication Services Select SPDR", "sector": "Communication Services", "color": "#e3b341"},
    "DRAM": {"name": "VanEck Semiconductor ETF", "sector": "Semiconductors", "color": "#c9d1d9"},
    "SOXX": {"name": "iShares Semiconductor ETF", "sector": "Semiconductors", "color": "#b392f0"},
    "EWY": {"name": "iShares MSCI South Korea ETF", "sector": "South Korea", "color": "#0075c9"},
    "IWM": {"name": "iShares Russell 2000 ETF", "sector": "Small Cap", "color": "#da3633"},
    "EWT": {"name": "iShares MSCI Taiwan ETF", "sector": "Taiwan", "color": "#2ea043"},
    "EWJ": {"name": "iShares MSCI Japan ETF", "sector": "Japan", "color": "#bc002d"},
    "NASA": {"name": "Procure Space ETF", "sector": "Space & Aerospace", "color": "#1f6feb"},
    "PEJ": {"name": "Invesco Leisure and Entertainment ETF", "sector": "Leisure & Entertainment", "color": "#f778ba"},
    "CIBR": {"name": "First Trust Nasdaq Cybersecurity ETF", "sector": "Cybersecurity", "color": "#56d364"},
    "GRID": {"name": "First Trust NASDAQ Clean Edge Smart Grid Infra ETF", "sector": "Clean Energy Grid", "color": "#39d353"},
    "QTUM": {"name": "Defiance Quantum ETF", "sector": "Quantum Computing", "color": "#8957e5"},
    "URA": {"name": "Global X Uranium ETF", "sector": "Uranium & Nuclear", "color": "#f0e68c"},
    "ITA": {"name": "iShares U.S. Aerospace & Defense ETF", "sector": "Aerospace & Defense", "color": "#6e7681"},
    "THRO": {"name": "iShares US Thematic Rotation Active ETF", "sector": "Thematic Rotation", "color": "#db61a2"},
    "IGV": {"name": "iShares Expanded Tech-Software Sector ETF", "sector": "Software", "color": "#4ac8e8"},
    "CHPY": {"name": "YieldMax Semiconductor Portfolio Option Income ETF", "sector": "Semiconductor Income", "color": "#e84646"},
}

ETF_SYMBOLS = list(SECTOR_ETFS.keys())
