ETF_INFO = {
    "SOXX": {
        "name": "iShares Semiconductor ETF",
        "description": "Tracks the ICE Semiconductor Index, providing exposure to U.S. companies in the semiconductor sector including chip designers, manufacturers, and equipment makers.",
        "sector": "Technology",
        "holdings": [
            {"ticker": "AVGO", "name": "Broadcom Inc."},
            {"ticker": "NVDA", "name": "NVIDIA Corporation"},
            {"ticker": "AMD",  "name": "Advanced Micro Devices"},
            {"ticker": "TXN",  "name": "Texas Instruments"},
            {"ticker": "QCOM", "name": "Qualcomm Inc."},
            {"ticker": "LRCX", "name": "Lam Research Corporation"},
            {"ticker": "KLAC", "name": "KLA Corporation"},
            {"ticker": "MRVL", "name": "Marvell Technology"},
            {"ticker": "MCHP", "name": "Microchip Technology"},
            {"ticker": "ON",   "name": "ON Semiconductor"},
        ],
    },
    "QQQ": {
        "name": "Invesco NASDAQ-100 ETF",
        "description": "Tracks the Nasdaq-100 Index, which includes 100 of the largest non-financial companies listed on the Nasdaq, heavily weighted toward technology and growth.",
        "sector": "Large-Cap Growth",
        "holdings": [
            {"ticker": "MSFT", "name": "Microsoft Corporation"},
            {"ticker": "AAPL", "name": "Apple Inc."},
            {"ticker": "NVDA", "name": "NVIDIA Corporation"},
            {"ticker": "AMZN", "name": "Amazon.com Inc."},
            {"ticker": "META", "name": "Meta Platforms Inc."},
            {"ticker": "GOOGL","name": "Alphabet Inc. Class A"},
            {"ticker": "GOOG", "name": "Alphabet Inc. Class C"},
            {"ticker": "TSLA", "name": "Tesla Inc."},
            {"ticker": "AVGO", "name": "Broadcom Inc."},
            {"ticker": "COST", "name": "Costco Wholesale"},
        ],
    },
    "SPY": {
        "name": "SPDR S&P 500 ETF Trust",
        "description": "The world's largest ETF by assets, tracking the S&P 500 Index. Provides broad exposure to 500 large-cap U.S. companies across all sectors, market-cap weighted.",
        "sector": "Large-Cap Blend",
        "holdings": [
            {"ticker": "MSFT", "name": "Microsoft Corporation"},
            {"ticker": "AAPL", "name": "Apple Inc."},
            {"ticker": "NVDA", "name": "NVIDIA Corporation"},
            {"ticker": "AMZN", "name": "Amazon.com Inc."},
            {"ticker": "META", "name": "Meta Platforms Inc."},
            {"ticker": "GOOGL","name": "Alphabet Inc. Class A"},
            {"ticker": "BRK-B","name": "Berkshire Hathaway Class B"},
            {"ticker": "LLY",  "name": "Eli Lilly and Company"},
            {"ticker": "AVGO", "name": "Broadcom Inc."},
            {"ticker": "JPM",  "name": "JPMorgan Chase & Co."},
        ],
    },
    "RSP": {
        "name": "Invesco S&P 500 Equal Weight ETF",
        "description": "Tracks the S&P 500 Equal Weight Index, giving each of the 500 companies an equal allocation (~0.2%). Reduces mega-cap concentration and tilts toward mid-cap value.",
        "sector": "Large-Cap Blend (Equal Weight)",
        "holdings": [
            {"ticker": "VST",  "name": "Vistra Corp"},
            {"ticker": "NRG",  "name": "NRG Energy Inc."},
            {"ticker": "PLTR", "name": "Palantir Technologies"},
            {"ticker": "DECK", "name": "Deckers Outdoor"},
            {"ticker": "DAL",  "name": "Delta Air Lines"},
            {"ticker": "UAL",  "name": "United Airlines Holdings"},
            {"ticker": "HWM",  "name": "Howmet Aerospace"},
            {"ticker": "LRCX", "name": "Lam Research Corporation"},
            {"ticker": "GE",   "name": "GE Aerospace"},
            {"ticker": "PWR",  "name": "Quanta Services"},
        ],
    },
    "NASA": {
        "name": "Procure Space ETF (UFO / Note: verify ticker)",
        "description": "Note: 'NASA' is not a standard ETF ticker. This may be a typo. Displaying data if available; verify intended ticker (e.g., ARKX for space exploration).",
        "sector": "Space / Thematic",
        "holdings": [
            {"ticker": "BA",   "name": "Boeing Company"},
            {"ticker": "LMT",  "name": "Lockheed Martin"},
            {"ticker": "NOC",  "name": "Northrop Grumman"},
            {"ticker": "RTX",  "name": "Raytheon Technologies"},
            {"ticker": "SPCE", "name": "Virgin Galactic Holdings"},
            {"ticker": "MAXR", "name": "Maxar Technologies"},
            {"ticker": "MNTS", "name": "Momentus Inc."},
            {"ticker": "RKLB", "name": "Rocket Lab USA"},
            {"ticker": "ASTS", "name": "AST SpaceMobile"},
            {"ticker": "SATL", "name": "Satellogic Inc."},
        ],
    },
    "MTUM": {
        "name": "iShares MSCI USA Momentum Factor ETF",
        "description": "Tracks large/mid-cap U.S. stocks with recent strong price momentum relative to peers. Holdings rotate based on 6- and 12-month price performance, capturing trend-following returns.",
        "sector": "Momentum Factor",
        "holdings": [
            {"ticker": "AAPL", "name": "Apple Inc."},
            {"ticker": "MSFT", "name": "Microsoft Corporation"},
            {"ticker": "NVDA", "name": "NVIDIA Corporation"},
            {"ticker": "META", "name": "Meta Platforms Inc."},
            {"ticker": "LLY",  "name": "Eli Lilly and Company"},
            {"ticker": "JPM",  "name": "JPMorgan Chase & Co."},
            {"ticker": "AMZN", "name": "Amazon.com Inc."},
            {"ticker": "AVGO", "name": "Broadcom Inc."},
            {"ticker": "PLTR", "name": "Palantir Technologies"},
            {"ticker": "V",    "name": "Visa Inc."},
        ],
    },
    "XLV": {
        "name": "Health Care Select Sector SPDR Fund",
        "description": "Tracks the Health Care sector of the S&P 500, including pharmaceuticals, biotechnology, medical devices, health insurance, and health-care services companies.",
        "sector": "Health Care",
        "holdings": [
            {"ticker": "LLY",  "name": "Eli Lilly and Company"},
            {"ticker": "UNH",  "name": "UnitedHealth Group"},
            {"ticker": "JNJ",  "name": "Johnson & Johnson"},
            {"ticker": "ABBV", "name": "AbbVie Inc."},
            {"ticker": "MRK",  "name": "Merck & Co. Inc."},
            {"ticker": "PFE",  "name": "Pfizer Inc."},
            {"ticker": "TMO",  "name": "Thermo Fisher Scientific"},
            {"ticker": "ABT",  "name": "Abbott Laboratories"},
            {"ticker": "DHR",  "name": "Danaher Corporation"},
            {"ticker": "AMGN", "name": "Amgen Inc."},
        ],
    },
    "XLF": {
        "name": "Financial Select Sector SPDR Fund",
        "description": "Tracks the Financials sector of the S&P 500, covering banks, insurance companies, capital markets, diversified financials, and real estate finance.",
        "sector": "Financials",
        "holdings": [
            {"ticker": "JPM",  "name": "JPMorgan Chase & Co."},
            {"ticker": "BRK-B","name": "Berkshire Hathaway Class B"},
            {"ticker": "V",    "name": "Visa Inc."},
            {"ticker": "MA",   "name": "Mastercard Inc."},
            {"ticker": "BAC",  "name": "Bank of America Corp."},
            {"ticker": "WFC",  "name": "Wells Fargo & Company"},
            {"ticker": "GS",   "name": "Goldman Sachs Group"},
            {"ticker": "MS",   "name": "Morgan Stanley"},
            {"ticker": "SPGI", "name": "S&P Global Inc."},
            {"ticker": "SCHW", "name": "Charles Schwab Corporation"},
        ],
    },
    "XLE": {
        "name": "Energy Select Sector SPDR Fund",
        "description": "Tracks the Energy sector of the S&P 500, including oil & gas exploration, production, refining, pipelines, and energy equipment & services companies.",
        "sector": "Energy",
        "holdings": [
            {"ticker": "XOM",  "name": "Exxon Mobil Corporation"},
            {"ticker": "CVX",  "name": "Chevron Corporation"},
            {"ticker": "COP",  "name": "ConocoPhillips"},
            {"ticker": "EOG",  "name": "EOG Resources Inc."},
            {"ticker": "SLB",  "name": "Schlumberger Ltd."},
            {"ticker": "MPC",  "name": "Marathon Petroleum Corp."},
            {"ticker": "VLO",  "name": "Valero Energy Corporation"},
            {"ticker": "PSX",  "name": "Phillips 66"},
            {"ticker": "WMB",  "name": "Williams Companies Inc."},
            {"ticker": "OKE",  "name": "ONEOK Inc."},
        ],
    },
    "XLI": {
        "name": "Industrial Select Sector SPDR Fund",
        "description": "Tracks the Industrials sector of the S&P 500, covering aerospace & defense, machinery, transportation, electrical equipment, and conglomerates.",
        "sector": "Industrials",
        "holdings": [
            {"ticker": "GE",   "name": "GE Aerospace"},
            {"ticker": "CAT",  "name": "Caterpillar Inc."},
            {"ticker": "HON",  "name": "Honeywell International"},
            {"ticker": "UNP",  "name": "Union Pacific Corporation"},
            {"ticker": "RTX",  "name": "Raytheon Technologies"},
            {"ticker": "DE",   "name": "Deere & Company"},
            {"ticker": "LMT",  "name": "Lockheed Martin Corp."},
            {"ticker": "ETN",  "name": "Eaton Corporation"},
            {"ticker": "ITW",  "name": "Illinois Tool Works"},
            {"ticker": "GD",   "name": "General Dynamics Corp."},
        ],
    },
    "XLY": {
        "name": "Consumer Discretionary Select Sector SPDR Fund",
        "description": "Tracks the Consumer Discretionary sector of the S&P 500, including retail, auto manufacturers, hotels, restaurants, leisure, and e-commerce companies.",
        "sector": "Consumer Discretionary",
        "holdings": [
            {"ticker": "AMZN", "name": "Amazon.com Inc."},
            {"ticker": "TSLA", "name": "Tesla Inc."},
            {"ticker": "HD",   "name": "Home Depot Inc."},
            {"ticker": "MCD",  "name": "McDonald's Corporation"},
            {"ticker": "BKNG", "name": "Booking Holdings Inc."},
            {"ticker": "LOW",  "name": "Lowe's Companies Inc."},
            {"ticker": "TJX",  "name": "TJX Companies Inc."},
            {"ticker": "NKE",  "name": "Nike Inc."},
            {"ticker": "SBUX", "name": "Starbucks Corporation"},
            {"ticker": "ROST", "name": "Ross Stores Inc."},
        ],
    },
    "XLP": {
        "name": "Consumer Staples Select Sector SPDR Fund",
        "description": "Tracks the Consumer Staples sector of the S&P 500, covering food & beverage, household products, personal care, tobacco, and discount retailers.",
        "sector": "Consumer Staples",
        "holdings": [
            {"ticker": "PG",   "name": "Procter & Gamble Co."},
            {"ticker": "WMT",  "name": "Walmart Inc."},
            {"ticker": "COST", "name": "Costco Wholesale Corp."},
            {"ticker": "KO",   "name": "Coca-Cola Company"},
            {"ticker": "PEP",  "name": "PepsiCo Inc."},
            {"ticker": "PM",   "name": "Philip Morris International"},
            {"ticker": "MDLZ", "name": "Mondelez International"},
            {"ticker": "MO",   "name": "Altria Group Inc."},
            {"ticker": "CL",   "name": "Colgate-Palmolive Co."},
            {"ticker": "GIS",  "name": "General Mills Inc."},
        ],
    },
    "XLB": {
        "name": "Materials Select Sector SPDR Fund",
        "description": "Tracks the Materials sector of the S&P 500, including chemicals, metals & mining, paper, forest products, and construction materials companies.",
        "sector": "Materials",
        "holdings": [
            {"ticker": "LIN",  "name": "Linde plc"},
            {"ticker": "SHW",  "name": "Sherwin-Williams Co."},
            {"ticker": "APD",  "name": "Air Products & Chemicals"},
            {"ticker": "FCX",  "name": "Freeport-McMoRan Inc."},
            {"ticker": "ECL",  "name": "Ecolab Inc."},
            {"ticker": "NUE",  "name": "Nucor Corporation"},
            {"ticker": "NEM",  "name": "Newmont Corporation"},
            {"ticker": "PPG",  "name": "PPG Industries Inc."},
            {"ticker": "CTVA", "name": "Corteva Inc."},
            {"ticker": "VMC",  "name": "Vulcan Materials Co."},
        ],
    },
    "XLRE": {
        "name": "Real Estate Select Sector SPDR Fund",
        "description": "Tracks the Real Estate sector of the S&P 500, covering REITs specializing in cell towers, data centers, industrial properties, retail, healthcare, and residential.",
        "sector": "Real Estate",
        "holdings": [
            {"ticker": "AMT",  "name": "American Tower Corp."},
            {"ticker": "PLD",  "name": "Prologis Inc."},
            {"ticker": "EQIX", "name": "Equinix Inc."},
            {"ticker": "CCI",  "name": "Crown Castle Inc."},
            {"ticker": "PSA",  "name": "Public Storage"},
            {"ticker": "DLR",  "name": "Digital Realty Trust"},
            {"ticker": "SPG",  "name": "Simon Property Group"},
            {"ticker": "WELL", "name": "Welltower Inc."},
            {"ticker": "SBAC", "name": "SBA Communications Corp."},
            {"ticker": "CBRE", "name": "CBRE Group Inc."},
        ],
    },
    "XLU": {
        "name": "Utilities Select Sector SPDR Fund",
        "description": "Tracks the Utilities sector of the S&P 500, covering electric utilities, multi-utilities, gas utilities, and independent power producers.",
        "sector": "Utilities",
        "holdings": [
            {"ticker": "NEE",  "name": "NextEra Energy Inc."},
            {"ticker": "SO",   "name": "Southern Company"},
            {"ticker": "DUK",  "name": "Duke Energy Corporation"},
            {"ticker": "AEP",  "name": "American Electric Power"},
            {"ticker": "SRE",  "name": "Sempra Energy"},
            {"ticker": "XEL",  "name": "Xcel Energy Inc."},
            {"ticker": "EXC",  "name": "Exelon Corporation"},
            {"ticker": "ED",   "name": "Consolidated Edison Inc."},
            {"ticker": "D",    "name": "Dominion Energy Inc."},
            {"ticker": "WEC",  "name": "WEC Energy Group Inc."},
        ],
    },
    "XLC": {
        "name": "Communication Services Select Sector SPDR Fund",
        "description": "Tracks the Communication Services sector of the S&P 500, including social media, streaming, telecom, interactive media, and entertainment companies.",
        "sector": "Communication Services",
        "holdings": [
            {"ticker": "META", "name": "Meta Platforms Inc."},
            {"ticker": "GOOGL","name": "Alphabet Inc. Class A"},
            {"ticker": "GOOG", "name": "Alphabet Inc. Class C"},
            {"ticker": "NFLX", "name": "Netflix Inc."},
            {"ticker": "TMUS", "name": "T-Mobile US Inc."},
            {"ticker": "CMCSA","name": "Comcast Corporation"},
            {"ticker": "DIS",  "name": "Walt Disney Company"},
            {"ticker": "VZ",   "name": "Verizon Communications"},
            {"ticker": "T",    "name": "AT&T Inc."},
            {"ticker": "EA",   "name": "Electronic Arts Inc."},
        ],
    },
}

ETF_SYMBOLS = list(ETF_INFO.keys())
