ETF_HOLDINGS = {
    "XLK": ["AAPL", "MSFT", "NVDA", "AVGO", "CRM", "ADBE", "AMD", "ACN", "CSCO", "ORCL"],
    "XLV": ["UNH", "LLY", "JNJ", "ABBV", "MRK", "TMO", "ABT", "DHR", "PFE", "AMGN"],
    "XLF": ["BRK-B", "JPM", "V", "MA", "BAC", "WFC", "GS", "MS", "SPGI", "BLK"],
    "XLE": ["XOM", "CVX", "EOG", "SLB", "MPC", "PSX", "VLO", "OXY", "COP", "HAL"],
    "XLI": ["CAT", "UNP", "HON", "RTX", "DE", "GE", "BA", "LMT", "UPS", "ETN"],
    "XLY": ["AMZN", "TSLA", "HD", "MCD", "NKE", "LOW", "SBUX", "TJX", "BKNG", "CMG"],
    "XLP": ["PG", "KO", "PEP", "COST", "WMT", "PM", "MO", "CL", "MDLZ", "KHC"],
    "XLB": ["LIN", "APD", "SHW", "FCX", "NEM", "ECL", "DD", "NUE", "VMC", "MLM"],
    "XLRE": ["PLD", "AMT", "CCI", "EQIX", "SPG", "PSA", "DLR", "O", "WELL", "VICI"],
    "XLU": ["NEE", "DUK", "SO", "D", "AEP", "SRE", "EXC", "XEL", "WEC", "ED"],
    "XLC": ["META", "GOOGL", "NFLX", "DIS", "CMCSA", "T", "VZ", "CHTR", "EA", "TTWO"],
    "DRAM": ["MU", "NXPI", "MRVL", "ON", "SWKS", "QRVO", "LSCC", "MPWR", "SLAB", "RMBS"],
    "SOXX": ["NVDA", "AMD", "AVGO", "INTC", "QCOM", "TXN", "LRCX", "AMAT", "MU", "ASML"],
    "EWY": ["PKX", "KB", "SHG", "LPL", "WF", "SKM", "KEP", "COUPF", "KT", "HMN"],
    "IWM": ["SMCI", "MARA", "RIOT", "AFRM", "UPST", "CELH", "DUOL", "TOST", "CAVA", "ANF"],
    "EWT": ["TSM", "UMC", "ASX", "CHPT", "IMOS", "SILC", "MPS", "AEHR", "HIMX", "WISA"],
    "EWJ": ["TM", "SONY", "MUFG", "HMC", "NMR", "SMFG", "IX", "NTDOY", "CAJ", "MFG"],
    "NASA": ["RKLB", "LMT", "BA", "NOC", "IRDM", "SPCE", "BKSY", "GSAT", "GILT", "MNTS"],
    "PEJ": ["MAR", "HLT", "RCL", "CCL", "NCLH", "MGM", "WYNN", "LVS", "DKNG", "CZR"],
    "CIBR": ["PANW", "CRWD", "FTNT", "ZS", "CYBR", "OKTA", "NET", "S", "TENB", "RPD"],
    "GRID": ["NEE", "ENPH", "FSLR", "PLUG", "BE", "RUN", "SEDG", "NOVA", "GEV", "VST"],
    "QTUM": ["IBM", "GOOGL", "IONQ", "RGTI", "QBTS", "HON", "MSFT", "ACLS", "MKSI", "ENTG"],
    "URA": ["CCJ", "NXE", "UEC", "DNN", "UUUU", "LEU", "SMR", "OKLO", "NNE", "LTBR"],
    "ITA": ["RTX", "LMT", "BA", "NOC", "GD", "TDG", "LHX", "HII", "HEI", "TXT"],
    "THRO": ["AAPL", "MSFT", "AMZN", "GOOGL", "META", "NVDA", "TSLA", "JPM", "V", "UNH"],
}
