STOCK_INFO = {
    "AAPL": {"name": "Apple Inc.", "industry": "Consumer Electronics"},
    "MSFT": {"name": "Microsoft Corp.", "industry": "Software"},
    "NVDA": {"name": "NVIDIA Corp.", "industry": "Semiconductors"},
    "AVGO": {"name": "Broadcom Inc.", "industry": "Semiconductors"},
    "CRM": {"name": "Salesforce Inc.", "industry": "Software"},
    "ADBE": {"name": "Adobe Inc.", "industry": "Software"},
    "AMD": {"name": "Advanced Micro Devices", "industry": "Semiconductors"},
    "ACN": {"name": "Accenture plc", "industry": "IT Services"},
    "CSCO": {"name": "Cisco Systems Inc.", "industry": "Networking"},
    "ORCL": {"name": "Oracle Corp.", "industry": "Software"},
    "UNH": {"name": "UnitedHealth Group", "industry": "Health Insurance"},
    "LLY": {"name": "Eli Lilly and Co.", "industry": "Pharmaceuticals"},
    "JNJ": {"name": "Johnson & Johnson", "industry": "Pharmaceuticals"},
    "ABBV": {"name": "AbbVie Inc.", "industry": "Pharmaceuticals"},
    "MRK": {"name": "Merck & Co.", "industry": "Pharmaceuticals"},
    "TMO": {"name": "Thermo Fisher Scientific", "industry": "Life Sciences"},
    "ABT": {"name": "Abbott Laboratories", "industry": "Medical Devices"},
    "DHR": {"name": "Danaher Corp.", "industry": "Life Sciences"},
    "PFE": {"name": "Pfizer Inc.", "industry": "Pharmaceuticals"},
    "AMGN": {"name": "Amgen Inc.", "industry": "Biotechnology"},
    "BRK-B": {"name": "Berkshire Hathaway", "industry": "Diversified Financials"},
    "JPM": {"name": "JPMorgan Chase & Co.", "industry": "Banking"},
    "V": {"name": "Visa Inc.", "industry": "Payment Services"},
    "MA": {"name": "Mastercard Inc.", "industry": "Payment Services"},
    "BAC": {"name": "Bank of America Corp.", "industry": "Banking"},
    "WFC": {"name": "Wells Fargo & Co.", "industry": "Banking"},
    "GS": {"name": "Goldman Sachs Group", "industry": "Investment Banking"},
    "MS": {"name": "Morgan Stanley", "industry": "Investment Banking"},
    "SPGI": {"name": "S&P Global Inc.", "industry": "Financial Data"},
    "BLK": {"name": "BlackRock Inc.", "industry": "Asset Management"},
    "XOM": {"name": "Exxon Mobil Corp.", "industry": "Oil & Gas"},
    "CVX": {"name": "Chevron Corp.", "industry": "Oil & Gas"},
    "EOG": {"name": "EOG Resources Inc.", "industry": "Oil & Gas"},
    "SLB": {"name": "Schlumberger Ltd.", "industry": "Oil Services"},
    "MPC": {"name": "Marathon Petroleum", "industry": "Oil Refining"},
    "PSX": {"name": "Phillips 66", "industry": "Oil Refining"},
    "VLO": {"name": "Valero Energy Corp.", "industry": "Oil Refining"},
    "OXY": {"name": "Occidental Petroleum", "industry": "Oil & Gas"},
    "COP": {"name": "ConocoPhillips", "industry": "Oil & Gas"},
    "HAL": {"name": "Halliburton Co.", "industry": "Oil Services"},
    "CAT": {"name": "Caterpillar Inc.", "industry": "Heavy Machinery"},
    "UNP": {"name": "Union Pacific Corp.", "industry": "Railroads"},
    "HON": {"name": "Honeywell International", "industry": "Diversified Industrials"},
    "RTX": {"name": "RTX Corp.", "industry": "Aerospace & Defense"},
    "DE": {"name": "Deere & Co.", "industry": "Farm Machinery"},
    "GE": {"name": "GE Aerospace", "industry": "Aerospace & Defense"},
    "BA": {"name": "Boeing Co.", "industry": "Aerospace & Defense"},
    "LMT": {"name": "Lockheed Martin Corp.", "industry": "Aerospace & Defense"},
    "UPS": {"name": "United Parcel Service", "industry": "Logistics"},
    "ETN": {"name": "Eaton Corp.", "industry": "Electrical Equipment"},
    "AMZN": {"name": "Amazon.com Inc.", "industry": "E-Commerce"},
    "TSLA": {"name": "Tesla Inc.", "industry": "Electric Vehicles"},
    "HD": {"name": "Home Depot Inc.", "industry": "Home Improvement Retail"},
    "MCD": {"name": "McDonald's Corp.", "industry": "Restaurants"},
    "NKE": {"name": "Nike Inc.", "industry": "Footwear & Apparel"},
    "LOW": {"name": "Lowe's Companies", "industry": "Home Improvement Retail"},
    "SBUX": {"name": "Starbucks Corp.", "industry": "Restaurants"},
    "TJX": {"name": "TJX Companies", "industry": "Discount Retail"},
    "BKNG": {"name": "Booking Holdings", "industry": "Online Travel"},
    "CMG": {"name": "Chipotle Mexican Grill", "industry": "Restaurants"},
    "PG": {"name": "Procter & Gamble", "industry": "Consumer Products"},
    "KO": {"name": "Coca-Cola Co.", "industry": "Beverages"},
    "PEP": {"name": "PepsiCo Inc.", "industry": "Beverages"},
    "COST": {"name": "Costco Wholesale", "industry": "Warehouse Clubs"},
    "WMT": {"name": "Walmart Inc.", "industry": "Discount Stores"},
    "PM": {"name": "Philip Morris Intl.", "industry": "Tobacco"},
    "MO": {"name": "Altria Group", "industry": "Tobacco"},
    "CL": {"name": "Colgate-Palmolive", "industry": "Consumer Products"},
    "MDLZ": {"name": "Mondelez International", "industry": "Packaged Foods"},
    "KHC": {"name": "Kraft Heinz Co.", "industry": "Packaged Foods"},
    "LIN": {"name": "Linde plc", "industry": "Industrial Gases"},
    "APD": {"name": "Air Products & Chemicals", "industry": "Industrial Gases"},
    "SHW": {"name": "Sherwin-Williams Co.", "industry": "Paints & Coatings"},
    "FCX": {"name": "Freeport-McMoRan", "industry": "Copper Mining"},
    "NEM": {"name": "Newmont Corp.", "industry": "Gold Mining"},
    "ECL": {"name": "Ecolab Inc.", "industry": "Specialty Chemicals"},
    "DD": {"name": "DuPont de Nemours", "industry": "Specialty Chemicals"},
    "NUE": {"name": "Nucor Corp.", "industry": "Steel"},
    "VMC": {"name": "Vulcan Materials", "industry": "Aggregates"},
    "MLM": {"name": "Martin Marietta Materials", "industry": "Aggregates"},
    "PLD": {"name": "Prologis Inc.", "industry": "Industrial REITs"},
    "AMT": {"name": "American Tower Corp.", "industry": "Tower REITs"},
    "CCI": {"name": "Crown Castle Inc.", "industry": "Tower REITs"},
    "EQIX": {"name": "Equinix Inc.", "industry": "Data Center REITs"},
    "SPG": {"name": "Simon Property Group", "industry": "Retail REITs"},
    "PSA": {"name": "Public Storage", "industry": "Storage REITs"},
    "DLR": {"name": "Digital Realty Trust", "industry": "Data Center REITs"},
    "O": {"name": "Realty Income Corp.", "industry": "Retail REITs"},
    "WELL": {"name": "Welltower Inc.", "industry": "Healthcare REITs"},
    "VICI": {"name": "VICI Properties", "industry": "Gaming REITs"},
    "NEE": {"name": "NextEra Energy", "industry": "Electric Utilities"},
    "DUK": {"name": "Duke Energy Corp.", "industry": "Electric Utilities"},
    "SO": {"name": "Southern Company", "industry": "Electric Utilities"},
    "D": {"name": "Dominion Energy", "industry": "Electric Utilities"},
    "AEP": {"name": "American Electric Power", "industry": "Electric Utilities"},
    "SRE": {"name": "Sempra", "industry": "Electric Utilities"},
    "EXC": {"name": "Exelon Corp.", "industry": "Electric Utilities"},
    "XEL": {"name": "Xcel Energy", "industry": "Electric Utilities"},
    "WEC": {"name": "WEC Energy Group", "industry": "Electric Utilities"},
    "ED": {"name": "Consolidated Edison", "industry": "Electric Utilities"},
    "META": {"name": "Meta Platforms Inc.", "industry": "Social Media"},
    "GOOGL": {"name": "Alphabet Inc.", "industry": "Internet Services"},
    "NFLX": {"name": "Netflix Inc.", "industry": "Streaming"},
    "DIS": {"name": "Walt Disney Co.", "industry": "Entertainment"},
    "CMCSA": {"name": "Comcast Corp.", "industry": "Cable & Media"},
    "T": {"name": "AT&T Inc.", "industry": "Telecom"},
    "VZ": {"name": "Verizon Communications", "industry": "Telecom"},
    "CHTR": {"name": "Charter Communications", "industry": "Cable & Media"},
    "EA": {"name": "Electronic Arts", "industry": "Video Games"},
    "TTWO": {"name": "Take-Two Interactive", "industry": "Video Games"},
    "MU": {"name": "Micron Technology", "industry": "Memory Chips"},
    "NXPI": {"name": "NXP Semiconductors", "industry": "Semiconductors"},
    "MRVL": {"name": "Marvell Technology", "industry": "Semiconductors"},
    "ON": {"name": "ON Semiconductor", "industry": "Semiconductors"},
    "SWKS": {"name": "Skyworks Solutions", "industry": "Semiconductors"},
    "QRVO": {"name": "Qorvo Inc.", "industry": "Semiconductors"},
    "LSCC": {"name": "Lattice Semiconductor", "industry": "Semiconductors"},
    "MPWR": {"name": "Monolithic Power Systems", "industry": "Semiconductors"},
    "SLAB": {"name": "Silicon Laboratories", "industry": "Semiconductors"},
    "RMBS": {"name": "Rambus Inc.", "industry": "Semiconductors"},
    "INTC": {"name": "Intel Corp.", "industry": "Semiconductors"},
    "QCOM": {"name": "Qualcomm Inc.", "industry": "Semiconductors"},
    "TXN": {"name": "Texas Instruments", "industry": "Semiconductors"},
    "LRCX": {"name": "Lam Research", "industry": "Semiconductor Equipment"},
    "AMAT": {"name": "Applied Materials", "industry": "Semiconductor Equipment"},
    "ASML": {"name": "ASML Holding", "industry": "Semiconductor Equipment"},
    "PKX": {"name": "POSCO Holdings", "industry": "Steel"},
    "KB": {"name": "KB Financial Group", "industry": "Banking"},
    "SHG": {"name": "Shinhan Financial", "industry": "Banking"},
    "LPL": {"name": "LG Display", "industry": "Display Technology"},
    "WF": {"name": "Woori Financial Group", "industry": "Banking"},
    "SKM": {"name": "SK Telecom", "industry": "Telecom"},
    "KEP": {"name": "Korea Electric Power", "industry": "Electric Utilities"},
    "COUPF": {"name": "Coupang Inc.", "industry": "E-Commerce"},
    "KT": {"name": "KT Corp.", "industry": "Telecom"},
    "HMN": {"name": "Horace Mann Educators", "industry": "Insurance"},
    "SMCI": {"name": "Super Micro Computer", "industry": "Computer Hardware"},
    "MARA": {"name": "Marathon Digital Holdings", "industry": "Crypto Mining"},
    "RIOT": {"name": "Riot Platforms", "industry": "Crypto Mining"},
    "AFRM": {"name": "Affirm Holdings", "industry": "Fintech"},
    "UPST": {"name": "Upstart Holdings", "industry": "Fintech"},
    "CELH": {"name": "Celsius Holdings", "industry": "Beverages"},
    "DUOL": {"name": "Duolingo Inc.", "industry": "EdTech"},
    "TOST": {"name": "Toast Inc.", "industry": "Restaurant Tech"},
    "CAVA": {"name": "CAVA Group", "industry": "Restaurants"},
    "ANF": {"name": "Abercrombie & Fitch", "industry": "Apparel Retail"},
    "TSM": {"name": "Taiwan Semiconductor", "industry": "Semiconductors"},
    "UMC": {"name": "United Microelectronics", "industry": "Semiconductors"},
    "ASX": {"name": "ASE Technology", "industry": "Semiconductor Packaging"},
    "CHPT": {"name": "ChargePoint Holdings", "industry": "EV Charging"},
    "IMOS": {"name": "ChipMOS Technologies", "industry": "Semiconductor Testing"},
    "SILC": {"name": "Silicom Ltd.", "industry": "Networking"},
    "MPS": {"name": "Monolithic Power Systems", "industry": "Semiconductors"},
    "AEHR": {"name": "Aehr Test Systems", "industry": "Semiconductor Equipment"},
    "HIMX": {"name": "Himax Technologies", "industry": "Display Drivers"},
    "WISA": {"name": "WiSA Technologies", "industry": "Audio Technology"},
    "TM": {"name": "Toyota Motor Corp.", "industry": "Automobiles"},
    "SONY": {"name": "Sony Group Corp.", "industry": "Consumer Electronics"},
    "MUFG": {"name": "Mitsubishi UFJ Financial", "industry": "Banking"},
    "HMC": {"name": "Honda Motor Co.", "industry": "Automobiles"},
    "NMR": {"name": "Nomura Holdings", "industry": "Investment Banking"},
    "SMFG": {"name": "Sumitomo Mitsui Financial", "industry": "Banking"},
    "IX": {"name": "ORIX Corp.", "industry": "Financial Services"},
    "NTDOY": {"name": "Nintendo Co.", "industry": "Video Games"},
    "CAJ": {"name": "Canon Inc.", "industry": "Imaging & Printing"},
    "MFG": {"name": "Mizuho Financial Group", "industry": "Banking"},
    "RKLB": {"name": "Rocket Lab USA", "industry": "Space Launch"},
    "NOC": {"name": "Northrop Grumman", "industry": "Aerospace & Defense"},
    "IRDM": {"name": "Iridium Communications", "industry": "Satellite Telecom"},
    "SPCE": {"name": "Virgin Galactic", "industry": "Space Tourism"},
    "BKSY": {"name": "BlackSky Technology", "industry": "Satellite Imaging"},
    "GSAT": {"name": "Globalstar Inc.", "industry": "Satellite Telecom"},
    "GILT": {"name": "Gilat Satellite Networks", "industry": "Satellite Networking"},
    "MNTS": {"name": "Momentus Inc.", "industry": "Space Infrastructure"},
    "MAR": {"name": "Marriott International", "industry": "Hotels"},
    "HLT": {"name": "Hilton Worldwide", "industry": "Hotels"},
    "RCL": {"name": "Royal Caribbean Cruises", "industry": "Cruise Lines"},
    "CCL": {"name": "Carnival Corp.", "industry": "Cruise Lines"},
    "NCLH": {"name": "Norwegian Cruise Line", "industry": "Cruise Lines"},
    "MGM": {"name": "MGM Resorts International", "industry": "Casinos & Gaming"},
    "WYNN": {"name": "Wynn Resorts", "industry": "Casinos & Gaming"},
    "LVS": {"name": "Las Vegas Sands", "industry": "Casinos & Gaming"},
    "DKNG": {"name": "DraftKings Inc.", "industry": "Online Gambling"},
    "CZR": {"name": "Caesars Entertainment", "industry": "Casinos & Gaming"},
    "PANW": {"name": "Palo Alto Networks", "industry": "Cybersecurity"},
    "CRWD": {"name": "CrowdStrike Holdings", "industry": "Cybersecurity"},
    "FTNT": {"name": "Fortinet Inc.", "industry": "Cybersecurity"},
    "ZS": {"name": "Zscaler Inc.", "industry": "Cybersecurity"},
    "CYBR": {"name": "CyberArk Software", "industry": "Cybersecurity"},
    "OKTA": {"name": "Okta Inc.", "industry": "Identity Security"},
    "NET": {"name": "Cloudflare Inc.", "industry": "Cloud Security"},
    "S": {"name": "SentinelOne Inc.", "industry": "Cybersecurity"},
    "TENB": {"name": "Tenable Holdings", "industry": "Cybersecurity"},
    "RPD": {"name": "Rapid7 Inc.", "industry": "Cybersecurity"},
    "ENPH": {"name": "Enphase Energy", "industry": "Solar Energy"},
    "FSLR": {"name": "First Solar Inc.", "industry": "Solar Energy"},
    "PLUG": {"name": "Plug Power Inc.", "industry": "Hydrogen/Fuel Cells"},
    "BE": {"name": "Bloom Energy", "industry": "Fuel Cells"},
    "RUN": {"name": "Sunrun Inc.", "industry": "Solar Energy"},
    "SEDG": {"name": "SolarEdge Technologies", "industry": "Solar Energy"},
    "NOVA": {"name": "Sunnova Energy", "industry": "Solar Energy"},
    "GEV": {"name": "GE Vernova", "industry": "Power Generation"},
    "VST": {"name": "Vistra Corp.", "industry": "Electric Utilities"},
    "IBM": {"name": "IBM Corp.", "industry": "IT Services"},
    "IONQ": {"name": "IonQ Inc.", "industry": "Quantum Computing"},
    "RGTI": {"name": "Rigetti Computing", "industry": "Quantum Computing"},
    "QBTS": {"name": "D-Wave Quantum", "industry": "Quantum Computing"},
    "ACLS": {"name": "Axcelis Technologies", "industry": "Semiconductor Equipment"},
    "MKSI": {"name": "MKS Instruments", "industry": "Scientific Instruments"},
    "ENTG": {"name": "Entegris Inc.", "industry": "Semiconductor Materials"},
    "CCJ": {"name": "Cameco Corp.", "industry": "Uranium Mining"},
    "NXE": {"name": "NexGen Energy", "industry": "Uranium Mining"},
    "UEC": {"name": "Uranium Energy Corp.", "industry": "Uranium Mining"},
    "DNN": {"name": "Denison Mines", "industry": "Uranium Mining"},
    "UUUU": {"name": "Energy Fuels Inc.", "industry": "Uranium Mining"},
    "LEU": {"name": "Centrus Energy", "industry": "Uranium Enrichment"},
    "SMR": {"name": "NuScale Power", "industry": "Nuclear Reactors"},
    "OKLO": {"name": "Oklo Inc.", "industry": "Nuclear Reactors"},
    "NNE": {"name": "Nano Nuclear Energy", "industry": "Nuclear Reactors"},
    "LTBR": {"name": "Lightbridge Corp.", "industry": "Nuclear Fuel"},
    "GD": {"name": "General Dynamics", "industry": "Aerospace & Defense"},
    "TDG": {"name": "TransDigm Group", "industry": "Aerospace Parts"},
    "LHX": {"name": "L3Harris Technologies", "industry": "Defense Electronics"},
    "HII": {"name": "Huntington Ingalls", "industry": "Shipbuilding"},
    "HEI": {"name": "HEICO Corp.", "industry": "Aerospace Parts"},
    "TXT": {"name": "Textron Inc.", "industry": "Aerospace & Defense"},
}


def _mock_pe(symbol):
    h = abs(hash(symbol + "pe")) % 1000
    if h < 50:
        return None
    return round(8 + (h % 60) + (h % 17) * 0.3, 1)


def get_stock_info(symbol, is_live=False):
    if is_live:
        try:
            import yfinance as yf
            info = yf.Ticker(symbol).info
            return {
                "company_name": info.get("shortName") or info.get("longName") or symbol,
                "industry": info.get("industry") or "Unknown",
                "pe_ratio": info.get("trailingPE"),
                "forward_pe": info.get("forwardPE"),
            }
        except Exception:
            pass

    mock = STOCK_INFO.get(symbol, {})
    return {
        "company_name": mock.get("name", symbol),
        "industry": mock.get("industry", "Unknown"),
        "pe_ratio": _mock_pe(symbol),
        "forward_pe": None,
    }
